CREATE TABLE days (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    
);

-- days should aslo have some identifier 
-- info like breakfast, lunch, etc.
-- maybe a meal_id ?? 