CREATE TABLE foods (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    days_id INTEGER REFERENCES days(id)
    meal_type TEXT, --bf/lunch/dinner/dessert
    -- meal_id INTEGER REFERENCES meal(id)
        ON DELETE CASCADE
);